CREATE DATABASE WishList
GO

USE WishList
GO

CREATE TABLE Usuario (
	Id INT IDENTITY PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Email VARCHAR(250) UNIQUE NOT NULL,
	Senha VARCHAR(250) NOT NULL
);

CREATE TABLE Desejo (
	Id INT IDENTITY PRIMARY KEY,
	Nome VARCHAR(100) NOT NULL,
	Descricao TEXT NOT NULL,
	DataCriacao DATETIME NOT NULL,
	UsuarioId INT NOT NULL FOREIGN KEY REFERENCES Usuario(Id)
);
