CREATE TABLE USUARIO(
	USUARIOID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(100) NOT NULL
	,EMAIL VARCHAR(250) UNIQUE NOT NULL
	,SENHA VARCHAR(250) NOT NULL
);

CREATE TABLE DESEJO(
	DESEJOID INT IDENTITY PRIMARY KEY
	,NOME VARCHAR(100) NOT NULL
	,DESCRICAO TEXT NOT NULL
	,DATACRICAO DATETIME NOT NULL
	,USUARIOID INT NOT NULL FOREIGN KEY REFERENCES USUARIO(USUARIOID)
);
